const vscode = require('vscode');
const fs = require('fs');
const path = require('path');

const RULES = [
  { 
    id: "SEC-001", 
    name: "OpenAI / Anthropic API Key", 
    regex: /sk-[a-zA-Z0-9_-]{20,70}/g, 
    severity: vscode.DiagnosticSeverity.Error,
    desc: "Committing active LLM tokens exposes active billing & infrastructure.",
    envKey: "OPENAI_API_KEY",
    envVar: "process.env.OPENAI_API_KEY"
  },
  { 
    id: "SEC-002", 
    name: "AWS Access Key ID", 
    regex: /(?:A3T[A-Z0-9]|AKIA[0-9A-Z]{16}|ASIA[0-9A-Z]{16})/g, 
    severity: vscode.DiagnosticSeverity.Error,
    desc: "Exposed AWS IAM credentials allow unauthorized cloud resource access.",
    envKey: "AWS_ACCESS_KEY_ID",
    envVar: "process.env.AWS_ACCESS_KEY_ID"
  },
  { 
    id: "SEC-003", 
    name: "Stripe Live Secret Key", 
    regex: /sk_live_[0-9a-zA-Z]{24,34}/g, 
    severity: vscode.DiagnosticSeverity.Error,
    desc: "Exposed payment processor keys allow unauthorized live financial transactions.",
    envKey: "STRIPE_SECRET_KEY",
    envVar: "process.env.STRIPE_SECRET_KEY"
  },
  { 
    id: "SEC-004", 
    name: "GitHub Personal Access Token", 
    regex: /gh[pousr]_[A-Za-z0-9_]{36,255}/g, 
    severity: vscode.DiagnosticSeverity.Warning,
    desc: "GitHub tokens expose private code repositories and CI/CD pipelines.",
    envKey: "GITHUB_TOKEN",
    envVar: "process.env.GITHUB_TOKEN"
  },
  { 
    id: "SEC-005", 
    name: "Google Cloud API Key", 
    regex: /AIza[0-9A-Za-z\-_]{35}/g, 
    severity: vscode.DiagnosticSeverity.Warning,
    desc: "Exposed GCP API keys enable unauthorized cloud quota usage.",
    envKey: "GCP_API_KEY",
    envVar: "process.env.GCP_API_KEY"
  },
  { 
    id: "SEC-006", 
    name: "Database Connection URI", 
    regex: /(?:postgres|mongodb(?:\+srv)?|mysql):\/\/[^:\s]+:[^@\s]+@[^/\s]+(?:\/[^\s]*)?/gi, 
    severity: vscode.DiagnosticSeverity.Error,
    desc: "Hardcoded database URI contains plaintext database credentials.",
    envKey: "DATABASE_URL",
    envVar: "process.env.DATABASE_URL"
  },
  { 
    id: "SEC-007", 
    name: "RSA / SSH Private Key Block", 
    regex: /-----BEGIN (?:RSA )?PRIVATE KEY-----/g, 
    severity: vscode.DiagnosticSeverity.Error,
    desc: "Raw asymmetric private key block exposed.",
    envKey: "PRIVATE_KEY",
    envVar: "process.env.PRIVATE_KEY"
  }
];

let diagnosticCollection;

function activate(context) {
  diagnosticCollection = vscode.languages.createDiagnosticCollection('gitscan-zero');
  context.subscriptions.push(diagnosticCollection);

  if (vscode.window.activeTextEditor) {
    scanDocument(vscode.window.activeTextEditor.document);
  }

  context.subscriptions.push(
    vscode.window.onDidChangeActiveTextEditor(editor => {
      if (editor) scanDocument(editor.document);
    }),
    vscode.workspace.onDidChangeTextDocument(event => {
      scanDocument(event.document);
    })
  );

  context.subscriptions.push(
    vscode.languages.registerCodeActionsProvider(
      { scheme: '*' },
      new SecretQuickFixProvider(),
      { providedCodeActionKinds: [vscode.CodeActionKind.QuickFix] }
    )
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('gitscan-zero.moveToEnvAndProtect', async (documentUri, range, envKey, envVar, rawSecret) => {
      const workspaceFolder = vscode.workspace.getWorkspaceFolder(documentUri);
      if (!workspaceFolder) {
        vscode.window.showErrorMessage('GitScan-Zero: No active workspace folder found.');
        return;
      }

      const rootPath = workspaceFolder.uri.fsPath;
      const envPath = path.join(rootPath, '.env');
      const gitignorePath = path.join(rootPath, '.gitignore');
      
      // Clean string from surrounding single/double quotes and whitespace
      const cleanSecret = rawSecret.replace(/^['"`]|['"`]$/g, '').trim();

      try {
        const edit = new vscode.WorkspaceEdit();
        edit.replace(documentUri, range, envVar);
        await vscode.workspace.applyEdit(edit);

        const envEntry = `\n${envKey}=${cleanSecret}\n`;
        if (fs.existsSync(envPath)) {
          fs.appendFileSync(envPath, envEntry, 'utf8');
        } else {
          fs.writeFileSync(envPath, `# Auto-generated by GitScan-Zero\n${envKey}=${cleanSecret}\n`, 'utf8');
        }

        let gitignoreUpdated = false;
        if (fs.existsSync(gitignorePath)) {
          const gitignoreContent = fs.readFileSync(gitignorePath, 'utf8');
          if (!gitignoreContent.includes('.env')) {
            fs.appendFileSync(gitignorePath, '\n# Added by GitScan-Zero\n.env\n', 'utf8');
            gitignoreUpdated = true;
          }
        } else {
          fs.writeFileSync(gitignorePath, '# GitScan-Zero Security Safeguard\n.env\nnode_modules\n', 'utf8');
          gitignoreUpdated = true;
        }

        vscode.window.showInformationMessage(
          `GitScan-Zero: ${envKey} secured in .env! ${gitignoreUpdated ? '(.env added to .gitignore)' : ''}`
        );
      } catch (err) {
        vscode.window.showErrorMessage(`GitScan-Zero Remediation Failed: ${err.message}`);
      }
    })
  );

  const statusBar = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
  statusBar.text = "$(shield) GitScan-Zero";
  statusBar.tooltip = "Air-Gapped Real-time Secret Protection Active";
  statusBar.show();
  context.subscriptions.push(statusBar);
}

function scanDocument(document) {
  if (!document) return;

  const text = document.getText();
  const diagnostics = [];

  RULES.forEach(rule => {
    const regex = new RegExp(rule.regex.source, rule.regex.flags);
    let match;
    while ((match = regex.exec(text)) !== null) {
      const lineStart = text.lastIndexOf('\n', match.index);
      const currentLine = text.substring(lineStart === -1 ? 0 : lineStart + 1, text.indexOf('\n', match.index) === -1 ? text.length : text.indexOf('\n', match.index));
      
      if (currentLine.includes('gitscan-ignore')) continue;

      const startPos = document.positionAt(match.index);
      const endPos = document.positionAt(match.index + match[0].length);
      const range = new vscode.Range(startPos, endPos);

      const message = `[GitScan-Zero - ${rule.id}] ${rule.name} detected. ${rule.desc}`;
      const diagnostic = new vscode.Diagnostic(range, message, rule.severity);
      
      diagnostic.code = {
        value: rule.id,
        target: vscode.Uri.parse(`https://github.com/samithatharanga/GitScan-Zero#${rule.id.toLowerCase()}`)
      };
      diagnostic.source = 'GitScan-Zero';
      diagnostics.push(diagnostic);
    }
  });

  diagnosticCollection.set(document.uri, diagnostics);
}

class SecretQuickFixProvider {
  provideCodeActions(document, range, context) {
    const actions = [];
    context.diagnostics
      .filter(diag => diag.source === 'GitScan-Zero')
      .forEach(diag => {
        const matchedRule = RULES.find(r => r.id === (typeof diag.code === 'object' ? diag.code.value : diag.code));
        const envKey = matchedRule ? matchedRule.envKey : 'SECRET_KEY';
        const envVarReplacement = matchedRule ? matchedRule.envVar : 'process.env.SECRET_KEY';
        const rawSecret = document.getText(diag.range);

        const autoEnvAction = new vscode.CodeAction(`Move to .env & Protect with .gitignore`, vscode.CodeActionKind.QuickFix);
        autoEnvAction.command = {
          command: 'gitscan-zero.moveToEnvAndProtect',
          title: 'Move to .env & Protect',
          arguments: [document.uri, diag.range, envKey, envVarReplacement, rawSecret]
        };
        autoEnvAction.isPreferred = true;
        actions.push(autoEnvAction);

        const redactAction = new vscode.CodeAction('Mask Secret with [REDACTED_SECRET]', vscode.CodeActionKind.QuickFix);
        redactAction.edit = new vscode.WorkspaceEdit();
        redactAction.edit.replace(document.uri, diag.range, '[REDACTED_SECRET]');
        actions.push(redactAction);

        const ignoreAction = new vscode.CodeAction('Suppress warning (Add // gitscan-ignore)', vscode.CodeActionKind.QuickFix);
        ignoreAction.edit = new vscode.WorkspaceEdit();
        const lineEnd = document.lineAt(diag.range.start.line).range.end;
        ignoreAction.edit.insert(document.uri, lineEnd, ' // gitscan-ignore');
        actions.push(ignoreAction);
      });
    return actions;
  }
}

function deactivate() {
  if (diagnosticCollection) {
    diagnosticCollection.clear();
  }
}

module.exports = { activate, deactivate };
